Add YAML support
aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE pull request #16
Opened 2020-10-02 23:43 UTC by ethankrein

Per the conversation in #8, this pull request adds YAML support.

By using YAML we get support for comments in our settings file eliminating the need for a settings_example file and making the process of entering credentials more user-friendly.

In this pr:
* Convert settings.txt to settings.yaml
* Add YAML support to all py files
* Update README to reflect the shift to settings.yaml

2020-10-03 12:44 UTC, fakeid30 commented
Brilliant job. I have added ROADMAP in another PR . Hope this goes to places.

2020-10-03 12:56 UTC, aapatre commented
Accepting! Can you please resolve the conflicts?

2020-10-03 13:05 UTC, fakeid30 requested changes
Please adjust webdriver names accordingly.

2020-10-03 13:05 UTC, fakeid30 commented on udemy_enroller_firefox.py
> +from webdriver_manager.microsoft import EdgeChromiumDriverManager
Why did you replace GeckoDriverManager with EdgeChromiumDriverManager in firefox ? this will break firefox. Please fix. @ethankrein @aapatre

2020-10-03 13:05 UTC, fakeid30 commented on udemy_enroller_opera.py
> +from webdriver_manager.microsoft import EdgeChromiumDriverManager
Shouldn't we use OperaDriverManager here instead of EdgeChromiumDriverManager? @ethankrein

2020-10-03 16:26 UTC, ethankrein commented
My apologies. I wasn't careful enough reviewing my work and I copied the edge imports into every file. Should be all good now.

2020-10-03 16:49 UTC, fakeid30 approved these changes

2020-10-04 07:07 UTC, merged

2020-10-04 07:11 UTC, aapatre commented
How about a dedicated chatroom for easier communication?

I've made a discord channel 
https://discord.gg/xDtGuf

2020-10-04 07:13 UTC, ethankrein commented
> How about a dedicated chatroom for easier communication?

I joined. I look forward to hearing from y'all.